[dc2_nxos_spines]
N-SPINE-01 ansible_host=192.168.1.31
N-SPINE-02 ansible_host=192.168.1.32

[dc2_nxos_leafs]
N-LEAF-01 ansible_host=192.168.1.51
N-LEAF-02 ansible_host=192.168.1.52
N-LEAF-03 ansible_host=192.168.1.53
N-LEAF-04 ansible_host=192.168.1.54
N-LEAF-05 ansible_host=192.168.1.55

[dc2_nxos:children]
dc2_nxos_spines
dc2_nxos_leafs

[dc2_ios_servers]
SRV21 ansible_host=192.168.1.80
SRV22 ansible_host=192.168.1.81
SRV23 ansible_host=192.168.1.82
SRV31 ansible_host=192.168.1.83
SRV32 ansible_host=192.168.1.84
SRV33 ansible_host=192.168.1.85

[dc2_nxos:vars]
ansible_network_os=cisco.nxos.nxos
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_password=Admin1234!
ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa'

[dc2_ios_servers:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_password=Admin1234!
ansible_become=yes
ansible_become_method=enable
