[dc2_spines]
N-SPINE-01  ansible_host=192.168.1.31
N-SPINE-02  ansible_host=192.168.1.32

[dc2_leaves]
N-LEAF-01   ansible_host=192.168.1.51
N-LEAF-02   ansible_host=192.168.1.52
N-LEAF-03   ansible_host=192.168.1.53
N-LEAF-04   ansible_host=192.168.1.54

[dc2_border]
N-LEAF-05   ansible_host=192.168.1.55

[dc2_fabric:children]
dc2_spines
dc2_leaves
dc2_border

[dc2_vpc_pair1]
N-LEAF-01   ansible_host=192.168.1.51
N-LEAF-02   ansible_host=192.168.1.52

[dc2_vpc_pair2]
N-LEAF-03   ansible_host=192.168.1.53
N-LEAF-04   ansible_host=192.168.1.54

[dc2_servers]
SRV21       ansible_host=192.168.1.80
SRV22       ansible_host=192.168.1.81
SRV23       ansible_host=192.168.1.82
SRV31       ansible_host=192.168.1.83
SRV32       ansible_host=192.168.1.84
SRV33       ansible_host=192.168.1.85

[dc2_ios:children]
dc2_servers

[dc2:children]
dc2_fabric
dc2_ios
