[dc1_nxos_spines]
F-SPINE-01 ansible_host=192.168.1.11
F-SPINE-02 ansible_host=192.168.1.12

[dc1_nxos_leafs]
F-LEAF-01 ansible_host=192.168.1.21
F-LEAF-02 ansible_host=192.168.1.22
F-LEAF-03 ansible_host=192.168.1.23
F-LEAF-04 ansible_host=192.168.1.24
F-LEAF-05 ansible_host=192.168.1.25

[dc1_nxos:children]
dc1_nxos_spines
dc1_nxos_leafs

[dc1_ios_servers]
SRV1  ansible_host=192.168.1.86
SRV2  ansible_host=192.168.1.87
SRV3  ansible_host=192.168.1.88
SRV11 ansible_host=192.168.1.89
SRV12 ansible_host=192.168.1.90
SRV13 ansible_host=192.168.1.91

[dc1_nxos:vars]
ansible_network_os=cisco.nxos.nxos
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_password=Admin1234!
ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa'

[dc1_ios_servers:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_password=Admin1234!
ansible_become=yes
ansible_become_method=enable
