[dc1_spines]
F-SPINE-01  ansible_host=192.168.1.11
F-SPINE-02  ansible_host=192.168.1.12

[dc1_leaves]
F-LEAF-01   ansible_host=192.168.1.21
F-LEAF-02   ansible_host=192.168.1.22
F-LEAF-03   ansible_host=192.168.1.23
F-LEAF-04   ansible_host=192.168.1.24

[dc1_border]
F-LEAF-05   ansible_host=192.168.1.25

[dc1_fabric:children]
dc1_spines
dc1_leaves
dc1_border

[dc1_vpc_pair1]
F-LEAF-01   ansible_host=192.168.1.21
F-LEAF-02   ansible_host=192.168.1.22

[dc1_vpc_pair2]
F-LEAF-03   ansible_host=192.168.1.23
F-LEAF-04   ansible_host=192.168.1.24

[dc1_servers]
SRV1        ansible_host=192.168.1.86
SRV2        ansible_host=192.168.1.87
SRV3        ansible_host=192.168.1.88
SRV11       ansible_host=192.168.1.89
SRV12       ansible_host=192.168.1.90
SRV13       ansible_host=192.168.1.91

[dc1_ios:children]
dc1_servers

[dc1:children]
dc1_fabric
dc1_ios
